version: '3.8'

services:
  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 40s
      timeout: 10s

  laravel:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt/live/erp.aroma-laundry.com:/etc/letsencrypt/live/erp.aroma-laundry.com
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=secret
    command: >
      bash -c "
        while ! nc -z db 3306; do
          echo 'Waiting for MySQL to be ready...' 
          sleep 5
        done
        composer install
        php artisan migrate --force
        php artisan key:generate
        npm install
        npm run build
        php-fpm
      "
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/letsencrypt/live/erp.aroma-laundry.com:/etc/letsencrypt/live/erp.aroma-laundry.com  
    ports:
      - "80:80"
      - "443:443"  
    depends_on:
      - laravel
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge